//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceStation
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Car
    {
        public Car()
        {
            this.Orders = new HashSet<Order>();
        }
        [Required(ErrorMessage = "Required field, select any number, in DB this field is autoincrement")]
        public int IdCar { get; set; }
        [Required(ErrorMessage = "Required field")]
        [RegularExpression("^[A-Za-z]+$", ErrorMessage = "Use symbols A-Z and a-z")]
        public string Make { get; set; }
        [Required(ErrorMessage = "Required field")]
        [RegularExpression("^[A-Za-z0-9]+$", ErrorMessage = "Use symbols A-Z, a-z, 0-9")]
        public string Model { get; set; }
        [Required(ErrorMessage = "Required field")]
        [Range(1950, 2016, ErrorMessage = "Enter number from 1950 to 2016")]
        public int Year { get; set; }
        [Required(ErrorMessage = "Required field")]
        [RegularExpression("^[A-Za-z0-9]+$", ErrorMessage = "Use symbols A-Z, a-z, 0-9")]
        public string VIN { get; set; }
        [Required(ErrorMessage = "Required field")]
        public int IdClient { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual ICollection<Order> Orders { get; set; }
    }
}
