//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceStation
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Client
    {
        public Client()
        {
            this.Cars = new HashSet<Car>();
        }
        [Required(ErrorMessage = "Required field, select any number, in DB this field is autoincrement")]
        public int IdClient { get; set; }
        [Required(ErrorMessage = "Required field")]
        [RegularExpression("^[A-Za-z]+$", ErrorMessage = "Use symbols A-Z and a-z")]
        public string Name { get; set; }
        [Required(ErrorMessage = "Required field")]
        [RegularExpression("^[A-Za-z]+$", ErrorMessage = "Use symbols A-Z and a-z")]
        public string Surname { get; set; }
        [Required(ErrorMessage = "Required field")]
        [DataType(DataType.Date, ErrorMessage = "Select date")]
        public string DateOfBirth { get; set; }
        [Required(ErrorMessage = "Required field")]
        [RegularExpression("^[A-Za-z,]+$", ErrorMessage = "Use symbols A-Z and a-z")]
        public string Address { get; set; }
        [Required(ErrorMessage = "Required field")]
        [RegularExpression("^[0-9]{7,9}$",ErrorMessage = "Use symbols 0-9 and length 7-9 symbols")]
        public string Phone { get; set; }
        [RegularExpression(@"[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,4}", ErrorMessage = "Incorrect adress")]
        public string Email { get; set; }
    
        public virtual ICollection<Car> Cars { get; set; }
    }
}
