//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceStation
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Order
    {
        [Required(ErrorMessage = "Required field, select any number, in DB this field is autoincrement")]
        public int IdOrder { get; set; }
        [Required(ErrorMessage = "Required field")]
        [DataType(DataType.Date,ErrorMessage = "Select date")]
        public System.DateTime Date { get; set; }
        [Required(ErrorMessage = "Required field")]
        [Range(0.0, 10000.0, ErrorMessage = "Enter amount from 0.0 to 10000.0")]
        public double OrderAmount { get; set; }
        [Required(ErrorMessage = "Required field")]
        [RegularExpression("^[A-Za-z ]+$",ErrorMessage = "Use symbols A-Z and a-z")]
        public string OrderStatus { get; set; }
        [Required(ErrorMessage = "Required field")]
        public int IdCar { get; set; }

        public virtual Car Car { get; set; }
    }
}
